language: r
pandoc_version: 1.19.2.1

#GITHUB_PAT created via web ui
#env:
#  global
#    - secure: A_LONG_ENCRYPTED_STRING

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
