# R at DHSC {#r_at_dhsc}

The following are the DHSC [sensible defaults](#sensible_defaults) for R:

## R Version & IDE
The dominant IDE for R is Rstudio, which comes packaged with R. 
For a new project you should use the latest version of Rstudio available from the software portal.

## General
Default to packages from the [Tidyverse](http://tidyverse.org/).These have been carefully designed to work together effectively as part of a modern data analysis workflow. More info can be found here: [R for Data Science by Hadley Wickham](http://r4ds.had.co.nz). 

For example:

   * Prefer tibbles to data.frames
   * Use ggplot2 rather than base graphics
   * Use the pipe `%>%` rather than nesting function calls. (...but not always e.g. see [here](https://twitter.com/hadleywickham/status/603883121197514752)).
   * Prefer `purrr` to the `apply` family of functions. See [here](http://r4ds.had.co.nz/iteration.html#the-map-functions)
   

## Packages {#r_default_packages}

Recommended Packages: 

* Data Manupulation and Tidying
    * [dplyr](https://dplyr.tidyverse.org/)
    * [tidyr](https://tidyr.tidyverse.org/)
* Working with messy spreadsheets
    * [tidyxl](https://nacnudus.github.io/tidyxl/)
    * [unpivotr](https://github.com/nacnudus/unpivotr)
* Working with large datasets:
    * [data.table](https://rdatatable.gitlab.io/data.table/)
    * [dtplyr](https://dtplyr.tidyverse.org/)
* Database Interface
    * [dbplyr](https://dbplyr.tidyverse.org/)
* Plotting
    * [ggplot2](https://ggplot2.tidyverse.org/)
    * [plotly](https://plot.ly/r/)
* Mapping
    * [sf](https://github.com/r-spatial/sf/)
    * [leaflet](http://rstudio.github.io/leaflet/)
* Reproducibility
    * [renv](https://rstudio.github.io/renv/)
* Producing gov.uk style output
    * [govstyle](http://ukgovdatascience.github.io/govstyle/index.html) (Government Theme for ggplot2)
    * [govdown](https://ukgovdatascience.github.io/govdown/)
* Machine Learning
    * [tensorflow](https://tensorflow.rstudio.com/)
    * [h2o](https://github.com/h2oai/h2o-3)
  

## Project Workflow {#r_projects}
Always work in a project. See the guide to [Using Projects](https://support.rstudio.com/hc/en-us/articles/200526207-Using-Projects).

Projects functionality is broken in DHSC's packaged version of Rstudio - see the fix [here](R/fix_projects.R)

## Packaging Your Code {#r_package}
Packages are the fundamental unit of reproducible R code. 
Therefore, if possible, build an R Package to share and document your code. 

Hadley's book on [R Packages](http://r-pkgs.had.co.nz/) is an effective guide on how to produce a package.

The [usethis](https://usethis.r-lib.org/) package has lots of useful shortcuts for package builders.

## Managing Dependencies {#r_dependencies}
There are two key competing ways of managing dependencies for an R Project:

* [`packrat`](https://rstudio.github.io/packrat/) - current established way to manage R dependencies
* [`renv`](https://rstudio.github.io/renv/) - rapidly maturing, successor to packrat.

See also:

* Rstudio page on [managing environments in R](https://environments.rstudio.com/)
* Rbloggers [post on renv](https://www.r-bloggers.com/reproducible-environments/)
* Rstudio page on combining [renv and docker](https://rstudio.github.io/renv/articles/docker.html)

### Using old versions of packages {#r_checkpoint}
You may come across code which doesn't work because it depends on a different version of a package to the one you have.

Fortunately, Microsoft keep daily snapshots of CRAN and store them on the [Microsoft R Application Network](https://mran.microsoft.com/timemachine).

The `checkpoint` package from Microsoft lets you use these snapshots to install packages as if it were any day since 2017-07-01.

Simply start your script with:
```{r eval=FALSE}
library(checkpoint)

checkpoint(snapshotDate = "2015-01-15",
           checkpointLocation = getwd()) 
```

This will download and fetch all the packages as they existed on the given date and install them to a library on your home drive.

Notes:

* If the code depends on `BH` (a lot of tidyverse code will) then this will take some time!
* By default checkpoint puts packages on your P drive - this will be slow.
    * You can use the `checkpointLocation` argument to tell checkpoint to use the C drive.

## Error Handling {#r_errorhandling}

Base R includes the `try()` and `tryCatch()` functions for handling errors. You can find an example of basic use of these on [r-bloggers](https://www.r-bloggers.com/error-handling-in-r/).

Effective error handling in R requires understanding the _conditions_ system. There is a good chapter on this in Hadley's [Advanced R book](https://adv-r.hadley.nz/conditions.html)

If you are iterating over many inputs, it is recommended that you use the `safely()` family of functions from `purrr` to create versions which return errors within a list for handling at a later stage.

## Unit Testing {#r_tests}
Use the `testthat` package for performing unit tests. 
For details see the ['tests' chapter of R Packages](https://r-pkgs.org/tests.html).
